/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Negocio.Tablero;
import com.itextpdf.text.DocumentException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class Principal extends javax.swing.JFrame {
    private Tablero tablero;
    private CrearPDF pdf = new CrearPDF();
    private boolean dirPeon;
    private javax.swing.JOptionPane mensaje;
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        panel1 = new java.awt.Panel();
        label1 = new java.awt.Label();
        panel2 = new java.awt.Panel();
        panel3 = new java.awt.Panel();
        label2 = new java.awt.Label();
        cboDireccion = new javax.swing.JComboBox<>();
        jugarBottom = new javax.swing.JButton();
        imprimirBottom = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        filaAlfil = new javax.swing.JTextField();
        columnaAlfil = new javax.swing.JTextField();
        filaPeon = new javax.swing.JTextField();
        columnaPeon = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        panel1.setBackground(new java.awt.Color(255, 255, 255));

        label1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label1.setText("Juego del Alfil");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
        );

        panel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
        );

        panel3.setBackground(new java.awt.Color(255, 255, 255));
        panel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label2.setText("Proyecto realizado por: Brayan Guerrero cód. 1151983 y Angie Orozco cód. 1151798");
        panel3.add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, -1, -1));

        cboDireccion.setBackground(new java.awt.Color(255, 255, 255));
        cboDireccion.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        cboDireccion.setForeground(new java.awt.Color(0, 0, 0));
        cboDireccion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ir hacia abajo", "Ir hacia arriba" }));
        cboDireccion.setToolTipText("");
        cboDireccion.setBorder(null);
        cboDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboDireccionActionPerformed(evt);
            }
        });
        panel3.add(cboDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(556, 65, -1, -1));

        jugarBottom.setBackground(new java.awt.Color(204, 204, 255));
        jugarBottom.setForeground(new java.awt.Color(0, 0, 0));
        jugarBottom.setText("Jugar");
        jugarBottom.setToolTipText("");
        jugarBottom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jugarBottomActionPerformed(evt);
            }
        });
        panel3.add(jugarBottom, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, -1, -1));

        imprimirBottom.setBackground(new java.awt.Color(204, 204, 255));
        imprimirBottom.setForeground(new java.awt.Color(0, 0, 0));
        imprimirBottom.setText("Imprimir");
        imprimirBottom.setToolTipText("");
        imprimirBottom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imprimirBottomActionPerformed(evt);
            }
        });
        panel3.add(imprimirBottom, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, -1, -1));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Fila:");
        panel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 72, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Columna:");
        panel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 109, -1, -1));

        filaAlfil.setBackground(new java.awt.Color(255, 255, 255));
        filaAlfil.setForeground(new java.awt.Color(0, 0, 0));
        filaAlfil.setMinimumSize(new java.awt.Dimension(25, 25));
        filaAlfil.setPreferredSize(new java.awt.Dimension(25, 25));
        panel3.add(filaAlfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 70, -1, -1));

        columnaAlfil.setBackground(new java.awt.Color(255, 255, 255));
        columnaAlfil.setForeground(new java.awt.Color(0, 0, 0));
        columnaAlfil.setPreferredSize(new java.awt.Dimension(25, 25));
        columnaAlfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                columnaAlfilActionPerformed(evt);
            }
        });
        panel3.add(columnaAlfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 107, -1, -1));

        filaPeon.setBackground(new java.awt.Color(255, 255, 255));
        filaPeon.setForeground(new java.awt.Color(0, 0, 0));
        filaPeon.setToolTipText("");
        filaPeon.setPreferredSize(new java.awt.Dimension(25, 25));
        panel3.add(filaPeon, new org.netbeans.lib.awtextra.AbsoluteConstraints(452, 68, -1, -1));

        columnaPeon.setBackground(new java.awt.Color(255, 255, 255));
        columnaPeon.setForeground(new java.awt.Color(0, 0, 0));
        columnaPeon.setPreferredSize(new java.awt.Dimension(25, 25));
        panel3.add(columnaPeon, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Fila:");
        panel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(382, 70, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Columna:");
        panel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(panel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboDireccionActionPerformed
        if(cboDireccion.getSelectedItem().toString().equals("Ir hacia abajo")) this.dirPeon = true;
        else this.dirPeon = false;
    }//GEN-LAST:event_cboDireccionActionPerformed

    private void jugarBottomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jugarBottomActionPerformed
        int i_alfil = Integer.parseInt(filaAlfil.getText());
        int j_alfil = Integer.parseInt(columnaAlfil.getText());
        int i_peon = Integer.parseInt(filaPeon.getText());
        int j_peon = Integer.parseInt(columnaPeon.getText());
        
        try {
            tablero = new Tablero(i_alfil, j_alfil, i_peon, j_peon, this.dirPeon);
            tablero.jugar();
            mensaje.showMessageDialog(null, "EL JUEGO YA FUE PROCESADO");
        } catch (Exception ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            mensaje.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_jugarBottomActionPerformed

    private void imprimirBottomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imprimirBottomActionPerformed
        try {
            pdf.crearPDF(tablero.getListaTableros(), tablero.getListaColas());
            mensaje.showMessageDialog(null, "SE HA CREADO EL PDF");
        } catch (DocumentException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            mensaje.showMessageDialog(null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            mensaje.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_imprimirBottomActionPerformed

    private void columnaAlfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_columnaAlfilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_columnaAlfilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboDireccion;
    private javax.swing.JTextField columnaAlfil;
    private javax.swing.JTextField columnaPeon;
    private javax.swing.JTextField filaAlfil;
    private javax.swing.JTextField filaPeon;
    private javax.swing.JButton imprimirBottom;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton jugarBottom;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Panel panel1;
    private java.awt.Panel panel2;
    private java.awt.Panel panel3;
    // End of variables declaration//GEN-END:variables
}
